export { default as MyTeam} from './MyTeam';
export { default as AllocatedSeats} from './AllocatedSeats';
export { default as MySupportTickets} from './MySupportTickets';
export { default as UpcomingBirthdays} from './UpcomingBirthdays';
export { default as UpcomingHolidays} from './UpcomingHolidays';
export { default as MyProjects} from './MyProjects';
export {default as Sidebar} from './Sidebar';
export {default as Dashboard} from './Dashboard';
export {default as Bonus} from './Bonus';
export {default as Login} from './Login';